version: '2.2'

services:
  authors-container:
    container_name: saffron-authors
    build:
      context: .
      dockerfile: authors/Dockerfile

  documentindex-container:
    container_name: saffron-documentindex
    build:
      context: .
      dockerfile: documentindex/Dockerfile

  taxonomy-container:
    container_name: saffron-taxonomy
    build:
      context: .
      dockerfile: taxonomy/Dockerfile

  term-similarity-container:
    container_name: saffron-term-similarity
    build:
      context: .
      dockerfile: topic/Dockerfile

  term-container:
    container_name: saffron-term
    build:
      context: .
      dockerfile: term/Dockerfile
