version: '2.2'

services:
  authors-container:
    container_name: saffron-authors
    build:
      context: .
      dockerfile: authors/Dockerfile

  documentindex-container:
    container_name: saffron-documentindex
    ports:
      - 9003:8080
    build:
      context: .
      dockerfile: documentindex/Dockerfile

  taxonomy-container:
    container_name: saffron-taxonomy
    ports:
      - 9002:8080
    build:
      context: .
      dockerfile: taxonomy/Dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  term-similarity-container:
    container_name: saffron-term-similarity
    ports:
      - 9004:8080
    build:
      context: .
      dockerfile: topic/Dockerfile

  term-container:
      container_name: saffron-term
      ports:
        - 9001:8080
      build:
        context: .
        dockerfile: term/Dockerfile
