version: '2.2'

volumes:
  saffron-model-volume:
    external: true

services:
  authors-container:
    container_name: saffron-authors
    ports:
      - 9002:8080
    build:
      context: .
      dockerfile: authors/Dockerfile
    volumes:
      - saffron-model-volume:/usr/local/app/models

  documentindex-container:
    container_name: saffron-documentindex
    ports:
      - 9000:8080
    build:
      context: .
      dockerfile: documentindex/Dockerfile
    volumes:
      - saffron-model-volume:/usr/local/app/models

  term-container:
    container_name: saffron-term
    build:
      context: .
      dockerfile: term/Dockerfile
    hostname: term
    ports:
      - 9001:8080
    volumes:
      - saffron-model-volume:/usr/local/app/models

  taxonomy-container:
     container_name: saffron-taxonomy
     ports:
           - 9005:8080
     environment:
      - JVM_OPTS=-Xmx3g -Xms3g -XX:MaxPermSize=1024m
     build:
       context: .
       dockerfile: taxonomy/Dockerfile
     volumes:
       - saffron-model-volume:/usr/local/app/models

  term-similarity-container:
    container_name: saffron-term-similarity
    ports:
          - 9004:8080
    build:
      context: .
      dockerfile: topic/Dockerfile

